[
  Loyalty.Application,
  LoyaltyWeb.Layouts,
  Loyalty.Repo,
  LoyaltyWeb.Telemetry,
  Mix.Tasks.Coverage.Index,
  LoyaltyWeb.ErrorHTML,
  LoyaltyWeb.LocaleController,
  LoyaltyWeb.Plugs.Locale,
  LoyaltyWeb.LoyaltyProgramLive.Show
]
